### PR TITLE
Merge missing commits from master into 0.2

### LINKED ISSUE #132: master branch is 36 commits ahead of 0.2.x
Hey @greg0ire (I assume you will be the person that knows the answer 😄 )!

We were trying to figure out why a method on `rst-parser` was missing over in - https://github.com/weaverryan/docs-builder/pull/27#discussion_r582176979 - and @nikophil discovered that some commits are only on `master` in this repository - https://github.com/doctrine/rst-parser/tree/master

Do you know how that happened? There are several few commits over there that I had originally made, and that we need. And do you think we can just merge master into 0.2.x?

Thanks!

### PR DESCRIPTION
**Pull request by weaverryan**
Hi!

This fixes #132. The following PR's had been merged into master, but were never added to 0.2:

* #100
* #106
* #107
* #108
* #109
* #110
* #111
* #112
* #113
* #114
* #115
* #118
* #119
* #122 
* #124

Thanks!

### CODE REVIEW

**Comment by greg0ire** [comment]
I think I confused everyone by releasing 0.2.0 when there were so many features added to `master` that are still unreleased. I noticed that many of them were added to milestone 1.0.0. IMO the best course of action would be to rename master to 1.0.x and then release 1.0.0. I just merged up 0.2.x into master, so nothing should be missing anywhere after that. Sorry again for the confusion, I had no idea there was that much divergence between both branches in the first place!

**Comment by greg0ire** [comment]
In fact, I notice that 1.0.x already exists (I must be the one who created it). So `master` can be removed instead of renamed.

**Comment by greg0ire** [comment]
Closing since IMO nothing is missing in 0.2.x. I notice you did some extra commits for cs and PHPstan, if you think they might be missing on 1.0.x please tell me, I will reopen and retarget.

**Comment by wouterj** [comment]
@greg0ire given those PRs are merged in 2019 en 2020, and 0.2.0 was released last week, I think it's fair to say that these are actually missing from 0.2.

I'm not sure about the roadmap/planning of Doctrine about this package. But if 1.0.0 will take some more time (read: weeks/months), I would like to know whether it's maybe possible to make a 0.3.0 with these changes?

**Comment by greg0ire** [comment]
@wouterj I was planning on releasing 1.0.0 tonight, since it seems to be blocking weaverryan/docs-builder . Any objections?

**Comment by greg0ire** [comment]
> I think it's fair to say that these are actually missing from 0.2.

I rather think I made a mistake by releasing 0.2 when I should really have release 1.0.0. Many PRs merged in 2019/2020 were put in that milestone a long time ago.

**Pull request closed without merging**
