### PR TITLE
[TASK] Make a failed test for multilevel toctrees

### PR DESCRIPTION
**Pull request by linawolf**
Failed test to demonstrate #197

### CODE REVIEW

**Comment by linawolf** [comment]
@greg0ire this is what I meant by subpages in a multi-level tree. Right now the behaviour of any toctree in the doctrine rst-parster is the same as if maxdepth=1 would be set. If the doctrine rst parser sets maxdepth=1 the behaviour is the same like if titlesonly was set in sphinx. However a change to this would be a breaking change. How do the projects feel about this? For us we really would need multi level menus as displayed in this test and as are common in sphinx

**Comment by greg0ire** [comment]
> However a change to this would be a breaking change.

If that is so, then you should target 0.6.x

@SenseException @wouterj @weaverryan , do you maybe have some idea of how breaking implementing this would be to the Doctrine or Symfony docs?

**Comment by weaverryan** [comment]
I'm not sure tbh. Symfony already has a lot of `:maxdepth: 1`, but I really am not sure. However, if it's a bug fix (regardless of if it's breaking), shouldn't we do it?

**Comment by linawolf** [comment]
@weaverryan If we merge #200 you would only have to replace all `:maxdepth: 1` with `:titlesonly` which should be straight forward

**Comment by wouterj** [comment]
If the change replicates what Sphinx is doing, this will not affect the Symfony docs. All toctree directives have been implemented when we were still using Sphinx IIRC.

**Comment by wouterj** [comment]
A quick code search on the Doctrine organisation shows that most of them are also using either depth or maxdepth. Except from most of the Doctrine1 documentation and these:

* https://github.com/doctrine/DoctrineCacheBundle/blob/7b690d59c361e429c741628e7338eb5e150d479d/Resources/doc/index.rst
* https://github.com/doctrine/doctrine-laminas-hydrator/blob/b76cfa71d5e494a8a71ada4e8ea6454fc0fc56ba/docs/en/index.rst
* https://github.com/doctrine/DoctrineORMModule/blob/bb27271954a96461a611ace772973257c33bc83a/docs/en/index.rst
* https://github.com/doctrine/couchdb-odm/blob/9bf3d8ed9a649d91b6a66aa439b05a8a1f1ef7fd/docs/en/index.rst
* https://github.com/doctrine/DoctrineBundle/blob/d2088fc50494e4e7441fecca54732245a613eeb6/Resources/doc/index.rst
* https://github.com/doctrine/DoctrineMongoODMModule/blob/1592e4bd4c851634a7a72737186caaa1d446c151/docs/en/index.rst

**Comment by greg0ire** [comment]
> shouldn't we do it ?

I'm just trying to assess if we should do it on 0.6.x or if 0.5.x is fine.

From what @wouterj is showing, I think it might be fine to stick with 0.5.x

**Comment by wouterj** [comment]
I would do it in 0.6 personally. It isn't necessarily more work to release either new minor or patch version, right? So in that case, doing the safe semver approach seems better to me

**Comment by greg0ire** [comment]
> It isn't necessarily more work to release either new minor or patch version, right?

Not that much more work, no. Let's follow your recommendation then. Converting to draft as a reminder.

**Comment by greg0ire** [comment]
Here is the PR to refresh 0.6.x: https://github.com/doctrine/rst-parser/pull/203

**Comment by SenseException** [comment]
> do you maybe have some idea of how breaking implementing this would be to the Doctrine or Symfony docs?

No idea. rst-parser didn't get many bigger changes that I could see as a reference.

**Comment by linawolf** [comment]
Not working on it anymore

**Pull request closed without merging**
