### PR TITLE
Fix for Toctree with Glob and wildcards

### LINKED ISSUE #183: Toctrees and Globs with wildcards don't seem to work
In the TYPO3 changelog we frequently work in toctrees with wildcarded globs, i.e.

```
Features
^^^^^^^^

.. toctree::
   :maxdepth: 1
   :titlesonly:
   :glob:

   Feature-*
```

To display all Feature Changelog entries. These work without issue in Sphinx but fail on the doctrine rst-parser

### PR DESCRIPTION
**Pull request by linawolf**
References https://github.com/doctrine/rst-parser/issues/183

### CODE REVIEW

**Comment by greg0ire** [comment]
The issue seems to be with this piece of code, which assumes `$globPatternPath` is always going to represent directories: https://github.com/doctrine/rst-parser/blob/d8a8d0849a2bfc28435c23702da2d63df38413c3/lib/Toc/GlobSearcher.php#L41-L43

**Comment by linawolf** [comment]
yeah working on that one right now to find a solution

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
To be squashed or squash-merged.

**Review by SenseException — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @linawolf !

**Comment by greg0ire** [comment]
:facepalm: I forgot to squash-merge, of course

**Pull request merged**
